# https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml

name: Deploy

on: [push, pull_request]
# See supported Node.js release schedule at https://nodejs.org/en/about/releases/
env:
  NODE_VERSION: 24
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Lint & Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        check-latest: true
        # cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    #- run: npm run dry-run
    - run: npm test --if-present

    # Prevent 'node_modules' etc. being deployed!
    - run: npm run clean
    - run: npm run move:404
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        # Upload one directory.
        path: .
        retention-days: 30
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

# End.
